
import java.rmi.Naming;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tllsp
 */
public class frmChucNangATM extends javax.swing.JFrame {

    /**
     * Creates new form frmChucNangATM
     */
    String tk, mk;
    public frmChucNangATM(String stk, String mk) {
        initComponents();
        this.tk=stk;
        this.mk=mk;
    }

    private frmChucNangATM() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnct = new javax.swing.JButton();
        btnrt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnnt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbten = new javax.swing.JLabel();
        btnsd = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        btnlsgd = new javax.swing.JButton();
        btndmk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnct.setBackground(new java.awt.Color(51, 153, 255));
        btnct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnct.setText("Chuyển tiền");
        btnct.setToolTipText("");
        btnct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnctActionPerformed(evt);
            }
        });

        btnrt.setBackground(new java.awt.Color(51, 153, 255));
        btnrt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnrt.setText("Rút tiền");
        btnrt.setToolTipText("");
        btnrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Vietinbank");

        btnnt.setBackground(new java.awt.Color(51, 153, 255));
        btnnt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnnt.setText("Nạp tiền");
        btnnt.setToolTipText("");
        btnnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnntActionPerformed(evt);
            }
        });

        jLabel2.setText("Xin chào, ");

        lbten.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnsd.setBackground(new java.awt.Color(51, 153, 255));
        btnsd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsd.setText("Xem số dư");
        btnsd.setToolTipText("");
        btnsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsdActionPerformed(evt);
            }
        });

        btnthoat.setBackground(new java.awt.Color(51, 153, 255));
        btnthoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.setToolTipText("");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        btnlsgd.setBackground(new java.awt.Color(51, 153, 255));
        btnlsgd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlsgd.setText("Lịch sử giao dịch");
        btnlsgd.setToolTipText("");
        btnlsgd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlsgdActionPerformed(evt);
            }
        });

        btndmk.setBackground(new java.awt.Color(51, 153, 255));
        btndmk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndmk.setText("Đổi mật khẩu");
        btndmk.setToolTipText("");
        btndmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndmkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbten, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btndmk, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnlsgd, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnrt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnct, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnnt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsd, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lbten))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnct)
                    .addComponent(btnrt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnt)
                    .addComponent(btnsd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlsgd)
                    .addComponent(btndmk))
                .addGap(33, 33, 33)
                .addComponent(btnthoat)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ITinhToan tt;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            tt = (ITinhToan) Naming.lookup("rmi://localhost:1099/TinhToan");
            lbten.setText(tt.hoten(tk));
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrtActionPerformed
        try {
            frmRutTien frmrt=new frmRutTien(tk,mk);
            frmrt.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_btnrtActionPerformed

    private void btnsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsdActionPerformed
        try {
            frmXemSoDu frmxsd=new frmXemSoDu(tk,mk);
            frmxsd.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnsdActionPerformed

    private void btnntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnntActionPerformed
        try {
            frmNapTien frmnt=new frmNapTien(tk, mk);
            frmnt.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnntActionPerformed

    private void btnctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnctActionPerformed
        try {
            frmChuyenTien frmct=new frmChuyenTien(tk, mk);
            frmct.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnctActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btnlsgdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlsgdActionPerformed
        frmLichSuGD frmls=new frmLichSuGD(tk, mk);
        frmls.setVisible(true); this.dispose();
    }//GEN-LAST:event_btnlsgdActionPerformed

    private void btndmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndmkActionPerformed
        frmDoiMatKhau frmdmk=new frmDoiMatKhau(tk, mk);
        frmdmk.setVisible(true); this.dispose();
    }//GEN-LAST:event_btndmkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChucNangATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChucNangATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChucNangATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChucNangATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChucNangATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnct;
    private javax.swing.JButton btndmk;
    private javax.swing.JButton btnlsgd;
    private javax.swing.JButton btnnt;
    private javax.swing.JButton btnrt;
    private javax.swing.JButton btnsd;
    private javax.swing.JButton btnthoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbten;
    // End of variables declaration//GEN-END:variables
}
