
import dao.dangnhapdao;
import java.rmi.Naming;
import javax.swing.JOptionPane;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tllsp
 */
public class frmRutTien extends javax.swing.JFrame {

    /**
     * Creates new form frmRutTien
     */
    String tk, mk;
    public frmRutTien(String tk, String mk) {
        initComponents();
        this.tk=tk;
        this.mk=mk;
    }

    private frmRutTien() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btn100 = new javax.swing.JButton();
        btn200 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        btn1000 = new javax.swing.JButton();
        btn2000 = new javax.swing.JButton();
        btn5000 = new javax.swing.JButton();
        txtnhapsotien = new javax.swing.JTextField();
        btn10000 = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        btndn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndn1.setForeground(new java.awt.Color(51, 102, 255));
        btndn1.setText("Đăng nhập");
        btndn1.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Vietinbank");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("MỜI QUÝ KHÁCH LỰA CHỌN SỐ TIỀN");
        jLabel2.setToolTipText("");

        btn100.setBackground(new java.awt.Color(51, 153, 255));
        btn100.setText("100.000");
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });

        btn200.setBackground(new java.awt.Color(51, 153, 255));
        btn200.setText("200.000");
        btn200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200ActionPerformed(evt);
            }
        });

        btn500.setBackground(new java.awt.Color(51, 153, 255));
        btn500.setText("500.000");
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });

        btnthoat.setBackground(new java.awt.Color(51, 153, 255));
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        btn1000.setBackground(new java.awt.Color(51, 153, 255));
        btn1000.setText("1.000.000");
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });

        btn2000.setBackground(new java.awt.Color(51, 153, 255));
        btn2000.setText("2.000.000");
        btn2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2000ActionPerformed(evt);
            }
        });

        btn5000.setBackground(new java.awt.Color(51, 153, 255));
        btn5000.setText("5.000.000");
        btn5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5000ActionPerformed(evt);
            }
        });

        btn10000.setBackground(new java.awt.Color(51, 153, 255));
        btn10000.setText("10.000.000");
        btn10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10000ActionPerformed(evt);
            }
        });

        btnok.setBackground(new java.awt.Color(51, 153, 255));
        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nhập số khác:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 95, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn200, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn2000, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn100, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn1000, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn500, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn5000, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnhapsotien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnok, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn10000, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn100)
                    .addComponent(btn1000))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn200)
                    .addComponent(btn2000))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn500)
                    .addComponent(btn5000))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthoat)
                    .addComponent(btn10000))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnhapsotien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnok)
                    .addComponent(jLabel3))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ITinhToan tt;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            tt = (ITinhToan) Naming.lookup("rmi://localhost:1099/TinhToan");
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        try {           
            long sotien=tt.sotien(tk);
            if(sotien>=100000){
                Date ngayrut=new java.util.Date();
                java.sql.Date sqlngayrut=new java.sql.Date(ngayrut.getTime());
                String ghichu="Rút tiền";
                tt.chitiettaikhoan(sqlngayrut, 100000, tk, ghichu);
                long sotiensaukhirut=sotien-100000;
                tt.ruttien(tk, sotiensaukhirut);

                frmRutTienTC frmrttc=new frmRutTienTC(tk, mk);
                frmrttc.setVisible(true);
                this.dispose();
            }else
                JOptionPane.showMessageDialog(this, "Số dư của bạn không đủ!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200ActionPerformed
        try {
            long sotien=tt.sotien(tk);
            if(sotien>=200000){
                Date ngayrut=new java.util.Date();
                java.sql.Date sqlngayrut=new java.sql.Date(ngayrut.getTime());
                String ghichu="Rút tiền";
                tt.chitiettaikhoan(sqlngayrut, 200000, tk, ghichu);
                long sotiensaukhirut=sotien-200000;
                tt.ruttien(tk, sotiensaukhirut);

                frmRutTienTC frmrttc=new frmRutTienTC(tk, mk);
                frmrttc.setVisible(true);
                this.dispose();
            }else
                JOptionPane.showMessageDialog(this, "Số dư của bạn không đủ!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn200ActionPerformed

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        try {
            long sotien=tt.sotien(tk);
            if(sotien>=500000){
                Date ngayrut=new java.util.Date();
                java.sql.Date sqlngayrut=new java.sql.Date(ngayrut.getTime());
                String ghichu="Rút tiền";
                tt.chitiettaikhoan(sqlngayrut, 500000, tk, ghichu);
                long sotiensaukhirut=sotien-500000;
                tt.ruttien(tk, sotiensaukhirut);

                frmRutTienTC frmrttc=new frmRutTienTC(tk, mk);
                frmrttc.setVisible(true);
                this.dispose();
            }else
                JOptionPane.showMessageDialog(this, "Số dư của bạn không đủ!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn500ActionPerformed

    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        try {
            long sotien=tt.sotien(tk);
            if(sotien>=1000000){
                Date ngayrut=new java.util.Date();
                java.sql.Date sqlngayrut=new java.sql.Date(ngayrut.getTime());
                String ghichu="Rút tiền";
                tt.chitiettaikhoan(sqlngayrut, 1000000, tk, ghichu);
                long sotiensaukhirut=sotien-1000000;
                tt.ruttien(tk, sotiensaukhirut);

                frmRutTienTC frmrttc=new frmRutTienTC(tk, mk);
                frmrttc.setVisible(true);
                this.dispose();
            }else
                JOptionPane.showMessageDialog(this, "Số dư của bạn không đủ!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn1000ActionPerformed

    private void btn2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2000ActionPerformed
        try {
            long sotien=tt.sotien(tk);
            if(sotien>=2000000){
                Date ngayrut=new java.util.Date();
                java.sql.Date sqlngayrut=new java.sql.Date(ngayrut.getTime());
                String ghichu="Rút tiền";
                tt.chitiettaikhoan(sqlngayrut, 2000000, tk, ghichu);
                long sotiensaukhirut=sotien-2000000;
                tt.ruttien(tk, sotiensaukhirut);

                frmRutTienTC frmrttc=new frmRutTienTC(tk, mk);
                frmrttc.setVisible(true);
                this.dispose();
            }else
                JOptionPane.showMessageDialog(this, "Số dư của bạn không đủ!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn2000ActionPerformed

    private void btn5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5000ActionPerformed
        try {
            long sotien=tt.sotien(tk);
            if(sotien>=5000000){
                Date ngayrut=new java.util.Date();
                java.sql.Date sqlngayrut=new java.sql.Date(ngayrut.getTime());
                String ghichu="Rút tiền";
                tt.chitiettaikhoan(sqlngayrut, 5000000, tk, ghichu);
                long sotiensaukhirut=sotien-5000000;
                tt.ruttien(tk, sotiensaukhirut);

                frmRutTienTC frmrttc=new frmRutTienTC(tk, mk);
                frmrttc.setVisible(true);
                this.dispose();
            }else
                JOptionPane.showMessageDialog(this, "Số dư của bạn không đủ!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn5000ActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btn10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10000ActionPerformed
        try {
            long sotien=tt.sotien(tk);
            if(sotien>=10000000){
                Date ngayrut=new java.util.Date();
                java.sql.Date sqlngayrut=new java.sql.Date(ngayrut.getTime());
                String ghichu="Rút tiền";
                tt.chitiettaikhoan(sqlngayrut, 10000000, tk, ghichu);
                long sotiensaukhirut=sotien-10000000;
                tt.ruttien(tk, sotiensaukhirut);

                frmRutTienTC frmrttc=new frmRutTienTC(tk, mk);
                frmrttc.setVisible(true);
                this.dispose();
            }else
                JOptionPane.showMessageDialog(this, "Số dư của bạn không đủ!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn10000ActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        try {
            long sotien=tt.sotien(tk);
            long sotienrut=Long.parseLong(txtnhapsotien.getText());
            if(sotien>=sotienrut){
                Date ngayrut=new java.util.Date();
                java.sql.Date sqlngayrut=new java.sql.Date(ngayrut.getTime());
                String ghichu="Rút tiền";
                tt.chitiettaikhoan(sqlngayrut, sotienrut, tk, ghichu);
                long sotiensaukhirut=sotien-sotienrut;
                tt.ruttien(tk, sotiensaukhirut);

                frmRutTienTC frmrttc=new frmRutTienTC(tk, mk);
                frmrttc.setVisible(true);
                this.dispose();
            }else
                JOptionPane.showMessageDialog(this, "Số dư của bạn không đủ!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRutTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn1000;
    private javax.swing.JButton btn10000;
    private javax.swing.JButton btn200;
    private javax.swing.JButton btn2000;
    private javax.swing.JButton btn500;
    private javax.swing.JButton btn5000;
    private javax.swing.JButton btndn1;
    private javax.swing.JButton btnok;
    private javax.swing.JButton btnthoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtnhapsotien;
    // End of variables declaration//GEN-END:variables
}
